services:
  app:
    build:
      context: ..
      dockerfile: ./app/Dockerfile
    ports:
      - 5000:5000
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - prometheus
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
